kind: Deployment
apiVersion: apps/v1
metadata:
   name: {{ include "webapp.fullname" . }}
spec:
   replicas: 2
   selector:
      matchLabels:
         app: webapp
   template:
      metadata:
         labels:
            app: webapp
      spec:
         containers:
            - name: webapp
              image:  {{ .Values.image.repository }}
              imagePullPolicy: Always
              ports:
                 - containerPort: 9090
