kind: Service
apiVersion: v1
metadata:
   name: {{ include "webapp.fullname" . }}
   labels:
      app: webapp
spec:
   ports:
      - port: 9090
        targetPort: 80
   selector:
      app: webapp
   type: LoadBalancer
